rule bwa_map:
    input:
        "data/genone.fa",
        "data/samples/A.fastq"
    output:
        "mapped_reads/A.bam"
    shell:
        "bwa mem {input} | "
        "samtools view -Sb - > {output}"